# Auto-generated by editor.server from editor/data/scenes/*.json.
# Do not edit manually.

AREA_DEFINITIONS = [('entrance_area', 'Entrance Area', (0.2, 0.35, 2.95, 3.25)),
 ('teacher_work_area', 'Teacher Work Area', (2.95, 0.35, 6.35, 4.25)),
 ('lore_display_area', 'Lore Display Area', (6.35, 0.35, 9.4, 3.2)),
 ('student_consult_area', 'Student Consult Area', (0.2, 3.25, 3.55, 6.35)),
 ('potion_brewing_area', 'Potion Brewing Area', (6.1, 3.2, 9.4, 6.85)),
 ('fireplace_area', 'Fireplace Area', (0.2, 6.35, 3.35, 9.75)),
 ('cleanup_area', 'Cleanup Area', (3.35, 6.35, 6.1, 9.75)),
 ('ingredient_storage_area', 'Ingredient Storage Area', (6.1, 6.85, 9.4, 9.75))]

AREA_METADATA = {'entrance_area': {},
 'teacher_work_area': {},
 'lore_display_area': {},
 'student_consult_area': {},
 'potion_brewing_area': {},
 'fireplace_area': {},
 'cleanup_area': {},
 'ingredient_storage_area': {}}

AREA_CHILD_AREAS = {}

AREA_WALL_DEFINITIONS = {}

AREA_PORTAL_DEFINITIONS = {}

AREA_RENDERING = {}

PORTAL_DEFINITIONS = [{'id': 'office_door_corridor_portal',
  'name': 'Office Door Corridor Portal',
  'kind': 'door',
  'areas': ['entrance_area', 'outside'],
  'segment': [[0.2, 1.0], [0.2, 2.2]]},
 {'id': 'entrance_work_opening',
  'name': 'Entrance Work Opening',
  'kind': 'opening',
  'areas': ['entrance_area', 'teacher_work_area'],
  'segment': [[2.95, 1.18], [2.95, 2.72]]},
 {'id': 'work_lore_opening',
  'name': 'Work Lore Opening',
  'kind': 'opening',
  'areas': ['teacher_work_area', 'lore_display_area'],
  'segment': [[6.35, 1.1], [6.35, 2.7]]},
 {'id': 'entrance_consult_opening',
  'name': 'Entrance Consult Opening',
  'kind': 'opening',
  'areas': ['entrance_area', 'student_consult_area'],
  'segment': [[0.95, 3.25], [2.7, 3.25]]},
 {'id': 'consult_work_opening',
  'name': 'Consult Work Opening',
  'kind': 'opening',
  'areas': ['student_consult_area', 'teacher_work_area'],
  'segment': [[3.55, 3.45], [3.55, 4.2]]},
 {'id': 'work_brewing_opening',
  'name': 'Work Brewing Opening',
  'kind': 'opening',
  'areas': ['teacher_work_area', 'potion_brewing_area'],
  'segment': [[6.1, 3.42], [6.1, 4.25]]},
 {'id': 'consult_fireplace_opening',
  'name': 'Consult Fireplace Opening',
  'kind': 'opening',
  'areas': ['student_consult_area', 'fireplace_area'],
  'segment': [[0.95, 6.35], [2.7, 6.35]]},
 {'id': 'fireplace_cleanup_opening',
  'name': 'Fireplace Cleanup Opening',
  'kind': 'opening',
  'areas': ['fireplace_area', 'cleanup_area'],
  'segment': [[3.35, 7.0], [3.35, 8.85]]},
 {'id': 'cleanup_ingredient_opening',
  'name': 'Cleanup Ingredient Opening',
  'kind': 'opening',
  'areas': ['cleanup_area', 'ingredient_storage_area'],
  'segment': [[6.1, 7.22], [6.1, 9.15]]},
 {'id': 'brewing_ingredient_opening',
  'name': 'Brewing Ingredient Opening',
  'kind': 'opening',
  'areas': ['potion_brewing_area', 'ingredient_storage_area'],
  'segment': [[7.1, 6.85], [8.95, 6.85]]}]

WALL_DEFINITIONS = []

ROAD_SEGMENT_DEFINITIONS = []

ROAD_INTERSECTION_DEFINITIONS = []

RENDERING = {'area_colors': {'entrance_area': '#6f5b47',
                 'teacher_work_area': '#8a5f32',
                 'lore_display_area': '#4d5f60',
                 'student_consult_area': '#4f694f',
                 'potion_brewing_area': '#5a6f55',
                 'fireplace_area': '#6f3f2a',
                 'cleanup_area': '#7d8278',
                 'ingredient_storage_area': '#7a6538'}}

POTIONS_TEACHER_OFFICE_DEFAULT_AGENT_START = [1.2, 2.72]
