# Auto-generated by editor.server from editor/data/scenes/*.json.
# Do not edit manually.

AREA_DEFINITIONS = [('kitchen', 'Kitchen', (0.2, 0.35, 4.1, 3.6)),
 ('dining_room', 'Dining Room', (4.1, 0.35, 6.5, 3.75)),
 ('bedroom', 'Bedroom', (6.55, 0.25, 9.15, 4.35)),
 ('entryway', 'Entryway', (0.2, 3.95, 2.25, 9.75)),
 ('living_room', 'Living Room', (2.25, 3.6, 7.05, 8.55)),
 ('bathroom', 'Bathroom', (7.05, 4.35, 9.15, 7.25)),
 ('main_balcony', 'Main Balcony', (2.35, 8.55, 7.05, 9.75)),
 ('utility_balcony', 'Utility Balcony', (7.05, 7.25, 9.15, 9.75))]

AREA_METADATA = {'kitchen': {},
 'dining_room': {},
 'bedroom': {},
 'entryway': {},
 'living_room': {},
 'bathroom': {},
 'main_balcony': {},
 'utility_balcony': {}}

AREA_CHILD_AREAS = {}

AREA_WALL_DEFINITIONS = {}

AREA_PORTAL_DEFINITIONS = {}

AREA_RENDERING = {}

PORTAL_DEFINITIONS = [{'id': 'front_door_portal',
  'name': 'Front Door Portal',
  'kind': 'door',
  'areas': ['entryway', 'outside'],
  'segment': [[0.2, 7.45], [0.2, 8.45]]},
 {'id': 'entry_living_opening',
  'name': 'Entry Living Opening',
  'kind': 'opening',
  'areas': ['entryway', 'living_room'],
  'segment': [[2.25, 5.1], [2.25, 8.1]]},
 {'id': 'kitchen_dining_opening',
  'name': 'Kitchen Dining Opening',
  'kind': 'opening',
  'areas': ['kitchen', 'dining_room'],
  'segment': [[4.1, 1.6], [4.1, 3.1]]},
 {'id': 'dining_living_opening',
  'name': 'Dining Living Opening',
  'kind': 'opening',
  'areas': ['dining_room', 'living_room'],
  'segment': [[4.1, 3.75], [6.4, 3.75]]},
 {'id': 'bedroom_door_portal',
  'name': 'Bedroom Door Portal',
  'kind': 'door',
  'areas': ['living_room', 'bedroom'],
  'segment': [[6.78, 3.68], [6.78, 4.28]]},
 {'id': 'bathroom_door_portal',
  'name': 'Bathroom Door Portal',
  'kind': 'door',
  'areas': ['living_room', 'bathroom'],
  'segment': [[7.05, 5.0], [7.05, 5.95]]},
 {'id': 'bathroom_utility_opening',
  'name': 'Bathroom Utility Opening',
  'kind': 'opening',
  'areas': ['bathroom', 'utility_balcony'],
  'segment': [[7.45, 7.25], [8.75, 7.25]]},
 {'id': 'living_main_balcony_glass_door',
  'name': 'Living Main Balcony Glass Door',
  'kind': 'glass_door',
  'areas': ['living_room', 'main_balcony'],
  'segment': [[3.4, 8.55], [5.4, 8.55]]}]

WALL_DEFINITIONS = []

ROAD_SEGMENT_DEFINITIONS = []

ROAD_INTERSECTION_DEFINITIONS = []

RENDERING = {'area_colors': {'kitchen': '#f1d2a8',
                 'dining_room': '#e6d994',
                 'bedroom': '#bdd7b4',
                 'entryway': '#d8c8bd',
                 'living_room': '#e6c89b',
                 'bathroom': '#afd6e6',
                 'main_balcony': '#bcdab7',
                 'utility_balcony': '#b7d8bf'}}

HOME_DEFAULT_AGENT_START = [3.1, 5.1]
