"""Data contracts for the agent subsystem.

Responsibility boundaries:
- Defines only data structures and enums; contains no execution logic.
- This module does not depend on the ran package; integration with ran is done through adapters/.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

AgentRole = Literal["student", "teacher", "staff"]
"""Role enum; when adding a new role, update configs/agents/roles.json accordingly."""

AgentActivityState = Literal[
    "idle",
    "planning",
    "walking",
    "network_pending",
    "network_active",
    "blocked",
    "done",
]
"""Activity states: planning=requesting/generating a plan; walking=moving along the path; network_pending=arrived, waiting to submit the intent;
network_active=service in progress (position frozen); blocked=plan or navigation failed; done=no more plans."""

IntentType = Literal["video_call", "video_upload", "file_transfer", "message"]
"""Intent type enum; traffic-volume conversion rules are in adapters/ran_intent_gateway.py."""

LoopPolicy = Literal["stop", "repeat"]
"""Behavior after template plans are exhausted: stop=end; repeat=loop from the start."""


@dataclass(frozen=True, slots=True)
class AgentPlan:
    """Semantic plan returned by the LLM or a template: only decides "where to go and what to do"; contains no coordinates."""

    agent_id: str  # agent_id: target agent.
    destination_ref: str  # destination_ref: semantic destination reference (full path/name/ID/alias).
    intent_type: IntentType  # intent_type: business intent type.
    intent_parameters: dict = field(default_factory=dict)  # intent_parameters: business parameters, e.g. size_profile / duration_seconds.
    stay: bool = False  # stay: True=no movement; submit the intent in place at the spawn position (channel-comparison templates).


@dataclass(frozen=True, slots=True)
class AgentSpawnDefinition:
    """Frozen definition of a single agent: identity, role, and spawn point."""

    agent_id: str  # agent_id: agent identifier frozen after scenario construction.
    role: AgentRole  # role: role.
    spawn_position: tuple[float, float]  # spawn_position: global spawn coordinates.
    ue_id: str | None = None  # ue_id: default UE identifier; generated by the registry when omitted.


@dataclass(frozen=True, slots=True)
class AgentPlanStep:
    """One step of a single agent's plan in a template."""

    destination_ref: str  # destination_ref: semantic destination reference.
    intent_type: IntentType  # intent_type: business intent type.
    intent_parameters: dict = field(default_factory=dict)  # intent_parameters: business parameters.
    stay: bool = False  # stay: True=no movement; submit the intent in place at the spawn position (channel-comparison templates).


@dataclass(frozen=True, slots=True)
class AgentSimulationDefinition:
    """Complete definition of one agent simulation (or test template); immutable after construction."""

    simulation_id: str  # simulation_id: global simulation identifier.
    agents: tuple[AgentSpawnDefinition, ...]  # agents: fixed agent set.
    plans: dict[str, tuple[AgentPlanStep, ...]] = field(default_factory=dict)  # plans: agent_id -> ordered plans (used in template mode).
    seed: int = 42  # seed: random seed; fixes candidate sampling and A* tie-breaking.
    loop_policy: LoopPolicy = "stop"  # loop_policy: behavior after plans are exhausted.
    llm_mode: bool = False  # llm_mode: True=LLM auto-direction; False=template mode.

    def __post_init__(self) -> None:
        if not self.simulation_id:
            raise ValueError("simulation_id must not be empty")
        if not self.agents:
            raise ValueError("An agent simulation must contain at least one agent")
        agent_ids = [item.agent_id for item in self.agents]
        if len(agent_ids) != len(set(agent_ids)):
            raise ValueError("agent_id values must be unique")
        unknown_plans = [key for key in self.plans if key not in set(agent_ids)]
        if unknown_plans:
            raise ValueError(f"plans reference unknown agents: {unknown_plans}")

    @property
    def agent_count(self) -> int:
        """Return the number of agents frozen at scenario construction time."""

        return len(self.agents)


@dataclass(slots=True)
class AgentSnapshot:
    """Read-only snapshot of a single agent at a given tick."""

    agent_id: str
    role: str
    lifecycle_status: str  # lifecycle_status: aligned with ran.AgentStatus: READY/ACTIVE/PAUSED/COMPLETED/FAILED.
    activity_state: str  # activity_state: planning/walking/network_active, etc.
    position: tuple[float, float]  # position: current global coordinates.
    current_room_id: str | None = None  # current_room_id: ID of the current area.
    destination_id: str | None = None  # destination_id: current destination semantic reference.
    current_intent_id: str | None = None  # current_intent_id: current intent ID.
    waypoint_index: int = 0  # waypoint_index: current waypoint index.
    waypoint_count: int = 0  # waypoint_count: total number of waypoints.
    last_transition_tick: int = 0  # last_transition_tick: tick of the most recent state transition.
    error: str | None = None  # error: most recent error message.
    waypoints: list = field(default_factory=list)  # waypoints: current planned path (list of world coordinates [x, y]); empty when not planned.

    def to_dict(self) -> dict:
        return {
            "agent_id": self.agent_id,
            "role": self.role,
            "lifecycle_status": self.lifecycle_status,
            "activity_state": self.activity_state,
            "position": list(self.position),
            "current_room_id": self.current_room_id,
            "destination_id": self.destination_id,
            "current_intent_id": self.current_intent_id,
            "waypoint_index": self.waypoint_index,
            "waypoint_count": self.waypoint_count,
            "last_transition_tick": self.last_transition_tick,
            "error": self.error,
            "waypoints": [list(point) for point in self.waypoints],
        }


@dataclass(slots=True)
class AgentStateFrame:
    """Full agent state frame for a given tick."""

    simulation_id: str
    tick: int
    agents: list[AgentSnapshot] = field(default_factory=list)
    plan_summary: list[dict] = field(default_factory=list)  # plan_summary: static task list (template mode, used by the frontend task panel).

    def to_dict(self) -> dict:
        return {
            "simulation_id": self.simulation_id,
            "tick": self.tick,
            "agents": [agent.to_dict() for agent in self.agents],
            "plan_summary": self.plan_summary,
        }
