# Auto-generated by editor.server from editor/data/scenes/*.json.
# Do not edit manually.

AREA_ELEMENTS = {'block_09_student_union': [{'node_id': 'student_union_desks',
                             'name': 'Desks',
                             'center': (393, 380),
                             'size': (16, 164),
                             'movable': True,
                             'locked': True,
                             'blocks_movement': False,
                             'physical_status': 'regular',
                             'evolution_status': 'stable',
                             'interaction_status': 'idle',
                             'state_details': {}}]}

BRISTOL_TOPOLOGY_BLOCKING_ELEMENT_IDS = set()
