# Auto-generated by editor.server from editor/data/scenes/*.json.
# Do not edit manually.

from __future__ import annotations

from ...scene_schema import Home
from ...scene_tree import build_scene_tree

from .elements import AREA_ELEMENTS, BRISTOL_TOPOLOGY_BLOCKING_ELEMENT_IDS
from .layout import (
    AREA_DEFINITIONS,
    AREA_METADATA,
    BRISTOL_TOPOLOGY_DEFAULT_AGENT_START,
    PORTAL_DEFINITIONS,
    RENDERING,
    ROAD_INTERSECTION_DEFINITIONS,
    ROAD_SEGMENT_DEFINITIONS,
    WALL_DEFINITIONS,
)


def build_bristol_topology_tree() -> Home:
    return build_scene_tree(
        scene_id='bristol_topology',
        scene_name='Bristol 2000x2000 topology',
        area_definitions=AREA_DEFINITIONS,
        area_elements=AREA_ELEMENTS,
        blocking_element_ids=BRISTOL_TOPOLOGY_BLOCKING_ELEMENT_IDS,
        default_agent_start=BRISTOL_TOPOLOGY_DEFAULT_AGENT_START,
        portal_definitions=PORTAL_DEFINITIONS,
        wall_definitions=WALL_DEFINITIONS,
        road_segment_definitions=ROAD_SEGMENT_DEFINITIONS,
        road_intersection_definitions=ROAD_INTERSECTION_DEFINITIONS,
        rendering=RENDERING,
        area_metadata=AREA_METADATA,
    )
